version: '3'

services:
  app:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: symfony-app
    ports:
      - "8000:8000" # Порт для Symfony
    volumes:
      - .:/var/www
    depends_on:
      - database
###> doctrine/doctrine-bundle ###
  database:
    container_name: postgres
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: postgres
      # You should definitely change the password in production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80" # Порт для Nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
